#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks-per-node=16
#SBATCH --partition=tc

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"


module load ams/2021.102
module list


$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

Task TransitionStateSearch 

TransitionStateSearch
    ReactionCoordinate
        Distance 3 2 -1.0
    End
End

System
  Atoms
C 0.81668 -0.234719 0.881975 
        C 0.816784 -0.234131 -0.477193 
        C -1.5316 -0.46998 -1.308576 
        H 0.856362 -1.163867 1.448593 
        C 0.738934 1.000635 1.660143 
        H -1.752243 -1.423246 -0.843669 
        H 0.865401 0.701495 -1.028794 
        H 0.997413 -1.142386 -1.042113 
        H -1.295721 -0.453222 -2.366756 
        H -1.934372 0.427296 -0.8548559999999999 
        O 0.730889 1.056221 2.881649 
        H 0.691474 1.935905 1.049596
  End
End

Properties
  NormalModes Yes
End
NormalModes
  ReScanFreqRange -10000000.0 20.0 
End

Engine ADF
  
  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY NOSYM
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA OLYP
  END
  
  NumericalQuality VERYGOOD
  Unrestricted Yes
  SpinPolarization 1.0
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.log

rm -r ams.results

