#!/bin/bash
#SBATCH -N 1
#SBATCH -t 240:00:00
#SBATCH --ntasks-per-node=4
#SBATCH --partition=tc

echo "== Starting run at $(date)"
echo "== Job ID: ${SLURM_JOBID}"
echo "== Node list: ${SLURM_NODELIST}"
echo "== Submit dir. : ${SLURM_SUBMIT_DIR}"
echo "== Scratch dir. : ${TMPDIR}"


module load ams/2021.102
module list


$AMSBIN/ams <<eor>$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.out

Task GeometryOptimization

System
  Atoms
H 2.053570374201116 -0.8034407316112255 0.0 
        C 0.9729371811798641 -0.695741129902268 0.0 
        H 0.6634665160798301 -0.1503511572353624 0.8866171636564089 
        H 0.6634665160798301 -0.1503511572353624 -0.8866171636564089 
         
  End
End

Properties
  NormalModes Yes
End
NormalModes
  ReScanFreqRange -10000000.0 20.0 
End

Engine ADF
  
  BASIS
     type TZ2P
     core none
  END
  
  SYMMETRY NOSYM
  
  SCF
     ITERATIONS 99
     Converge 1.0e-6 
  END
  
  XC
    GGA OLYP
  END
  
  NumericalQuality VERYGOOD
  Unrestricted Yes
  SpinPolarization 1.0
ENDEngine

eor

cp ams.results/ams.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.ams.rkf
cp ams.results/adf.rkf $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.adf.rkf
cp ams.results/ams.log $SLURM_SUBMIT_DIR/$SLURM_JOB_NAME.log

rm -r ams.results

